wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1659103055
    t:
      1:
      - 1
      - 5
      - 11
      - 31
      - 41
      - 49
      - 51
      3:
      - 13
      4: 3.9.7
      5: 0.12.11
      6: 4.17.0
      8:
      - 1
      - 5
