In [1]:
import pandas as pd
import numpy

## Create the mappings

In [83]:
# Open the sheet with the mappings
mapping_sheet = pd.read_csv("Data-Preparation/Joint-mapping-of-all-three-schemata.csv")
mapping_sheet.head(3)

Category X-GENRE joint schema From the initial schema
0  A1 (argumentative)            discarded                     FTD
1        A17 (review)            discarded                     FTD
2              Advice            discarded                    CORE

In [84]:
# Create mappings from the sheet
map_df_FTD = mapping_sheet[mapping_sheet["From the initial schema"] == "FTD"]
map_df_CORE = mapping_sheet[mapping_sheet["From the initial schema"] == "CORE"]
map_df_GINCO = mapping_sheet[mapping_sheet["From the initial schema"] == "GINCO"]

map_df_GINCO

Category     X-GENRE joint schema  \
7                          FAQ                discarded   
12  List of Summaries/Excerpts                discarded   
27                       Forum                    Forum   
31     Information/Explanation  Information/Explanation   
33            Research Article  Information/Explanation   
36                 Instruction              Instruction   
38                      Recipe              Instruction   
42            Legal/Regulation                    Legal   
44                Announcement                     News   
46              News/Reporting                     News   
47            Opinionated News                     News   
54       Opinion/Argumentation    Opinion/Argumentation   
57                      Review    Opinion/Argumentation   
59                        Call                    Other   
60              Correspondence                    Other   
62                   Interview                    Other   
63                       Other                    Other   
64                Script/Drama                    Other   
68                  Invitation                Promotion   
69                   Promotion                Promotion   
70      Promotion of a Product                Promotion   
71       Promotion of Services                Promotion   
72                     Lyrical            Prose/Lyrical   
75                       Prose            Prose/Lyrical   

   From the initial schema  
7                    GINCO  
12                   GINCO  
27                   GINCO  
31                   GINCO  
33                   GINCO  
36                   GINCO  
38                   GINCO  
42                   GINCO  
44                   GINCO  
46                   GINCO  
47                   GINCO  
54                   GINCO  
57                   GINCO  
59                   GINCO  
60                   GINCO  
62                   GINCO  
63                   GINCO  
64                   GINCO  
68                   GINCO  
69                   GINCO  
70                   GINCO  
71                   GINCO  
72                   GINCO  
75                   GINCO

In [10]:
# Create dictionary mappings
map_FTD = {x:y for x,y in zip(map_df_FTD["Category"], map_df_FTD["X-GENRE joint schema"])}

print(map_FTD)

{'A1 (argumentative)': 'discarded', 'A17 (review)': 'discarded', 'A14 (academic)': 'Information/Explanation', 'A16 (information)': 'Information/Explanation', 'A7 (instruction)': 'Instruction', 'A9 (legal)': 'Legal', 'A8 (news)': 'News', 'A11 (personal)': 'Opinion/Argumentation', 'A12 (promotion)': 'Promotion', 'A4 (fiction)': 'Prose/Lyrical'}


In [85]:
map_CORE = {x:y for x,y in zip(map_df_CORE["Category"], map_df_CORE["X-GENRE joint schema"])}

print(map_CORE)

{'Advice': 'discarded', 'Course Materials': 'discarded', 'Description of a Person': 'discarded', 'Description of a Thing': 'discarded', 'Description with Intent to Sell': 'discarded', 'FAQ about How-to': 'discarded', 'FAQ about Information': 'discarded', 'Historical Article': 'discarded', 'Information Blog': 'discarded', 'Magazine Article': 'discarded', 'Other Forum': 'discarded', 'Other Information': 'discarded', 'Other Informational Persuasion': 'discarded', 'Other Opinion': 'discarded', 'Other Spoken': 'discarded', 'Poem': 'discarded', 'Question/Answer Forum': 'discarded', 'Reader/Viewer Responses': 'discarded', 'Religious Blogs/Sermons': 'discarded', 'Technical Report': 'discarded', 'Transcript of Video/Audio': 'discarded', 'Travel Blog': 'discarded', 'Discussion Forum': 'Forum', 'Encyclopedia Article': 'Information/Explanation', 'Research Article': 'Information/Explanation', 'How-to': 'Instruction', 'Recipe': 'Instruction', 'Technical Support': 'Instruction', 'Legal terms': 'Legal

In [12]:
map_GINCO = {x:y for x,y in zip(map_df_GINCO["Category"], map_df_GINCO["X-GENRE joint schema"])}

print(map_GINCO)

{'FAQ': 'discarded', 'List of Summaries/Excerpts': 'discarded', 'Forum': 'Forum', 'Information/Explanation': 'Information/Explanation', 'Research Article': 'Information/Explanation', 'Instruction': 'Instruction', 'Recipe': 'Instruction', 'Legal/Regulation': 'Legal', 'Announcement': 'News', 'News/Reporting': 'News', 'Opinionated News': 'News', 'Opinion/Argumentation': 'Opinion/Argumentation', 'Review': 'Opinion/Argumentation', 'Call': 'Other', 'Correspondence': 'Other', 'Interview': 'Other', 'Other': 'Other', 'Script/Drama': 'Other', 'Invitation': 'Promotion', 'Promotion': 'Promotion', 'Promotion of a Product': 'Promotion', 'Promotion of Services': 'Promotion', 'Lyrical': 'Prose/Lyrical', 'Prose': 'Prose/Lyrical'}


```
map_FTD = {'A1 (argumentative)': 'discarded', 'A17 (review)': 'discarded', 'A14 (academic)': 'Information/Explanation', 'A16 (information)': 'Information/Explanation', 'A7 (instruction)': 'Instruction', 'A9 (legal)': 'Legal', 'A8 (news)': 'News', 'A11 (personal)': 'Opinion/Argumentation', 'A12 (promotion)': 'Promotion', 'A4 (fiction)': 'Prose/Lyrical'}

map_GINCO = {'FAQ': 'discarded', 'List of Summaries/Excerpts': 'discarded', 'Forum': 'Forum', 'Information/Explanation': 'Information/Explanation', 'Research Article': 'Information/Explanation', 'Instruction': 'Instruction', 'Recipe': 'Instruction', 'Legal/Regulation': 'Legal', 'Announcement': 'News', 'News/Reporting': 'News', 'Opinionated News': 'News', 'Opinion/Argumentation': 'Opinion/Argumentation', 'Review': 'Opinion/Argumentation', 'Call': 'Other', 'Correspondence': 'Other', 'Interview': 'Other', 'Other': 'Other', 'Script/Drama': 'Other', 'Invitation': 'Promotion', 'Promotion': 'Promotion', 'Promotion of a Product': 'Promotion', 'Promotion of Services': 'Promotion', 'Lyrical': 'Prose/Lyrical', 'Prose': 'Prose/Lyrical'}


map_CORE = {'Advice': 'discarded', 'Course Materials': 'discarded', 'Description of a Person': 'discarded', 'Description of a Thing': 'discarded', 'Description with Intent to Sell': 'discarded', 'FAQ about How-to': 'discarded', 'FAQ about Information': 'discarded', 'Historical Article': 'discarded', 'Information Blog': 'discarded', 'Magazine Article': 'discarded', 'Other Forum': 'discarded', 'Other Information': 'discarded', 'Other Informational Persuasion': 'discarded', 'Other Opinion': 'discarded', 'Other Spoken': 'discarded', 'Poem': 'discarded', 'Question/Answer Forum': 'discarded', 'Reader/Viewer Responses': 'discarded', 'Religious Blogs/Sermons': 'discarded', 'Technical Report': 'discarded', 'Transcript of Video/Audio': 'discarded', 'Travel Blog': 'discarded', 'Discussion Forum': 'Forum', 'Encyclopedia Article': 'Information/Explanation', 'Research Article': 'Information/Explanation', 'How-to': 'Instruction', 'Recipe': 'Instruction', 'Technical Support': 'Instruction', 'Legal terms': 'Legal', 'News Report/Blog': 'News', 'Sports Report': 'News', 'Editorial': 'Opinion/Argumentation', 'Formal Speech': 'Opinion/Argumentation', 'Letter to Editor': 'Opinion/Argumentation', 'Opinion Blog': 'Opinion/Argumentation', 'Personal Blog': 'Opinion/Argumentation', 'Persuasive Article or Essay': 'Opinion/Argumentation', 'Reviews': 'Opinion/Argumentation', 'Interview': 'Other', 'TV/Movie Script': 'Other', 'Advertisement': 'Promotion', 'Prayer': 'Prose/Lyrical', 'Short Story': 'Prose/Lyrical', 'Song Lyrics': 'Prose/Lyrical', 'Other Narrative': 'discarded', 'Other Lyrical': 'discarded', 'Other How-to': 'discarded'}

```

## Apply mapping to GINCO sheet

In [31]:
# Apply mapping to the sheet with all information

GINCO_sheet = pd.read_csv("data-sheets-with-all-info/GINCO-MT-GINCO-keeptext-with-all-information.csv", sep = "\t", index_col= 0)
GINCO_sheet.head(5)

id                                                url  crawled   hard  \
0  3949  http://www.pomurje.si/aktualno/sport/zimska-li...     2014  False   
1  3726  http://www.ss-sezana.si/sss/index.php?option=c...     2014  False   
2  5621  http://www.kamnik-starejsi.si/novice/144-sodel...     2014  False   
3  3776  http://www.radiocelje.si/novica.php?id=13007&a...     2014  False   
4  2102  http://www.mtv.si/novice/selena-gomez-ponudila...     2014  False   

           primary_level_1          primary_level_2          primary_level_3  \
0           News/Reporting           News/Reporting           News/Reporting   
1  Information/Explanation  Information/Explanation  Information/Explanation   
2    Promotion of Services    Promotion of Services                Promotion   
3           News/Reporting           News/Reporting           News/Reporting   
4         Opinionated News         Opinionated News         Opinionated News   

       secondary_level_1      secondary_level_2      secondary_level_3  ...  \
0                    NaN                    NaN                    NaN  ...   
1                    NaN                    NaN                    NaN  ...   
2  Opinion/Argumentation  Opinion/Argumentation  Opinion/Argumentation  ...   
3                    NaN                    NaN                    NaN  ...   
4                    NaN                    NaN                    NaN  ...   

  text_length     FTD_pred_on_SL     FTD_pred_on_MT  \
0          93          A8 (news)          A8 (news)   
1          76  A16 (information)  A16 (information)   
2         232    A12 (promotion)    A12 (promotion)   
3         158          A8 (news)          A8 (news)   
4          63          A8 (news)          A8 (news)   

  split-without-rare-categories          primary_level_4 downcast_split  \
0                          test           News/Reporting           test   
1                          test  Information/Explanation            dev   
2                         train                Promotion           test   
3                         train           News/Reporting          train   
4                          test           News/Reporting          train   

                    CORE_main_pred_on_SL  \
0                              Narrative   
1  Informational Description/Explanation   
2  Informational Description/Explanation   
3  Informational Description/Explanation   
4                              Narrative   

                    CORE_main_pred_on_MT     CORE_sub_pred_on_SL  \
0                              Narrative           Sports Report   
1  Informational Description/Explanation  Description of a Thing   
2  Informational Description/Explanation  Description of a Thing   
3  Informational Description/Explanation        News Report/Blog   
4                              Narrative        News Report/Blog   

      CORE_sub_pred_on_MT  
0           Sports Report  
1  Description of a Thing  
2  Description of a Thing  
3        News Report/Blog  
4        News Report/Blog  

[5 rows x 28 columns]

In [32]:
GINCO_sheet["primary_level_1_to_X-GENRE"] = GINCO_sheet["primary_level_1"].map(map_GINCO)

GINCO_sheet["primary_level_1_to_X-GENRE"]

0                          News
1       Information/Explanation
2                     Promotion
3                          News
4                          News
                 ...           
997     Information/Explanation
998                   discarded
999                   discarded
1000      Opinion/Argumentation
1001                  discarded
Name: primary_level_1_to_X-GENRE, Length: 1002, dtype: object

In [33]:
# Check whether there is any NaN value in the column with mappings GINCO_sheet
GINCO_sheet[GINCO_sheet["primary_level_1_to_X-GENRE"].isnull().values]

Empty DataFrame
Columns: [id, url, crawled, hard, primary_level_1, primary_level_2, primary_level_3, secondary_level_1, secondary_level_2, secondary_level_3, tertiary_level_1, tertiary_level_2, tertiary_level_3, split, domain, GINCORE, Slovene_text, MT_text, text_length, FTD_pred_on_SL, FTD_pred_on_MT, split-without-rare-categories, primary_level_4, downcast_split, CORE_main_pred_on_SL, CORE_main_pred_on_MT, CORE_sub_pred_on_SL, CORE_sub_pred_on_MT, primary_level_1_to_X-GENRE]
Index: []

[0 rows x 29 columns]

In [34]:
# Save the new GINCO sheet
GINCO_sheet.to_csv("data-sheets-with-all-info/GINCO-MT-GINCO-keeptext-with-all-information.csv", sep = "\t")

In [35]:
# Analyze distribution of labels according to the new mapping
count = pd.DataFrame({"Count": list(GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts()), "Percentage": list(GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts(normalize=True))}, index = GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts().index)

print(count.to_markdown())

|                         |   Count |   Percentage |
|:------------------------|--------:|-------------:|
| News                    |     221 |   0.220559   |
| Promotion               |     209 |   0.208583   |
| Information/Explanation |     139 |   0.138723   |
| Opinion/Argumentation   |     131 |   0.130739   |
| discarded               |     109 |   0.108782   |
| Other                   |      70 |   0.0698603  |
| Forum                   |      52 |   0.0518962  |
| Instruction             |      44 |   0.0439122  |
| Legal                   |      17 |   0.0169661  |
| Prose/Lyrical           |      10 |   0.00998004 |


In [36]:
# Discard the "discarded" labels to calculate distribution without them
GINCO_sheet = GINCO_sheet[GINCO_sheet["primary_level_1_to_X-GENRE"] != "discarded"]

GINCO_sheet.describe()

crawled  text_length
count   893.000000   893.000000
mean   2017.409854   357.256439
std       3.500800   474.135102
min    2014.000000    12.000000
25%    2014.000000    96.000000
50%    2014.000000   192.000000
75%    2021.000000   409.000000
max    2021.000000  4134.000000

In [40]:
count = pd.DataFrame({"Count": list(GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts()), "Percentage": list(round(GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts(normalize=True)*100, 2))}, index = GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts().index)

print(count.to_markdown())

|                         |   Count |   Percentage |
|:------------------------|--------:|-------------:|
| News                    |     221 |        24.75 |
| Promotion               |     209 |        23.4  |
| Information/Explanation |     139 |        15.57 |
| Opinion/Argumentation   |     131 |        14.67 |
| Other                   |      70 |         7.84 |
| Forum                   |      52 |         5.82 |
| Instruction             |      44 |         4.93 |
| Legal                   |      17 |         1.9  |
| Prose/Lyrical           |      10 |         1.12 |


In [ ]:
# Apply mapping to the sheet with all information

GINCO_sheet = pd.read_csv("data-sheets-with-all-info/GINCO-MT-GINCO-keeptext-with-all-information.csv", sep = "\t", index_col= 0)
GINCO_sheet.head(5)

id                                                url  crawled   hard  \
0  3949  http://www.pomurje.si/aktualno/sport/zimska-li...     2014  False   
1  3726  http://www.ss-sezana.si/sss/index.php?option=c...     2014  False   
2  5621  http://www.kamnik-starejsi.si/novice/144-sodel...     2014  False   
3  3776  http://www.radiocelje.si/novica.php?id=13007&a...     2014  False   
4  2102  http://www.mtv.si/novice/selena-gomez-ponudila...     2014  False   

           primary_level_1          primary_level_2          primary_level_3  \
0           News/Reporting           News/Reporting           News/Reporting   
1  Information/Explanation  Information/Explanation  Information/Explanation   
2    Promotion of Services    Promotion of Services                Promotion   
3           News/Reporting           News/Reporting           News/Reporting   
4         Opinionated News         Opinionated News         Opinionated News   

       secondary_level_1      secondary_level_2      secondary_level_3  ...  \
0                    NaN                    NaN                    NaN  ...   
1                    NaN                    NaN                    NaN  ...   
2  Opinion/Argumentation  Opinion/Argumentation  Opinion/Argumentation  ...   
3                    NaN                    NaN                    NaN  ...   
4                    NaN                    NaN                    NaN  ...   

  text_length     FTD_pred_on_SL     FTD_pred_on_MT  \
0          93          A8 (news)          A8 (news)   
1          76  A16 (information)  A16 (information)   
2         232    A12 (promotion)    A12 (promotion)   
3         158          A8 (news)          A8 (news)   
4          63          A8 (news)          A8 (news)   

  split-without-rare-categories          primary_level_4 downcast_split  \
0                          test           News/Reporting           test   
1                          test  Information/Explanation            dev   
2                         train                Promotion           test   
3                         train           News/Reporting          train   
4                          test           News/Reporting          train   

                    CORE_main_pred_on_SL  \
0                              Narrative   
1  Informational Description/Explanation   
2  Informational Description/Explanation   
3  Informational Description/Explanation   
4                              Narrative   

                    CORE_main_pred_on_MT     CORE_sub_pred_on_SL  \
0                              Narrative           Sports Report   
1  Informational Description/Explanation  Description of a Thing   
2  Informational Description/Explanation  Description of a Thing   
3  Informational Description/Explanation        News Report/Blog   
4                              Narrative        News Report/Blog   

      CORE_sub_pred_on_MT  
0           Sports Report  
1  Description of a Thing  
2  Description of a Thing  
3        News Report/Blog  
4        News Report/Blog  

[5 rows x 28 columns]

In [ ]:
GINCO_sheet["primary_level_1_to_X-GENRE"] = GINCO_sheet["primary_level_1"].map(map_GINCO)

GINCO_sheet["primary_level_1_to_X-GENRE"]

0                          News
1       Information/Explanation
2                     Promotion
3                          News
4                          News
                 ...           
997     Information/Explanation
998                   discarded
999                   discarded
1000      Opinion/Argumentation
1001                  discarded
Name: primary_level_1_to_X-GENRE, Length: 1002, dtype: object

In [ ]:
# Check whether there is any NaN value in the column with mappings GINCO_sheet
GINCO_sheet[GINCO_sheet["primary_level_1_to_X-GENRE"].isnull().values]

Empty DataFrame
Columns: [id, url, crawled, hard, primary_level_1, primary_level_2, primary_level_3, secondary_level_1, secondary_level_2, secondary_level_3, tertiary_level_1, tertiary_level_2, tertiary_level_3, split, domain, GINCORE, Slovene_text, MT_text, text_length, FTD_pred_on_SL, FTD_pred_on_MT, split-without-rare-categories, primary_level_4, downcast_split, CORE_main_pred_on_SL, CORE_main_pred_on_MT, CORE_sub_pred_on_SL, CORE_sub_pred_on_MT, primary_level_1_to_X-GENRE]
Index: []

[0 rows x 29 columns]

In [ ]:
# Save the new GINCO sheet
GINCO_sheet.to_csv("data-sheets-with-all-info/GINCO-MT-GINCO-keeptext-with-all-information.csv", sep = "\t")

In [ ]:
# Analyze distribution of labels according to the new mapping
count = pd.DataFrame({"Count": list(GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts()), "Percentage": list(GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts(normalize=True))}, index = GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts().index)

print(count.to_markdown())

|                         |   Count |   Percentage |
|:------------------------|--------:|-------------:|
| News                    |     221 |   0.220559   |
| Promotion               |     209 |   0.208583   |
| Information/Explanation |     139 |   0.138723   |
| Opinion/Argumentation   |     131 |   0.130739   |
| discarded               |     109 |   0.108782   |
| Other                   |      70 |   0.0698603  |
| Forum                   |      52 |   0.0518962  |
| Instruction             |      44 |   0.0439122  |
| Legal                   |      17 |   0.0169661  |
| Prose/Lyrical           |      10 |   0.00998004 |


In [ ]:
# Discard the "discarded" labels to calculate distribution without them
GINCO_sheet = GINCO_sheet[GINCO_sheet["primary_level_1_to_X-GENRE"] != "discarded"]

GINCO_sheet.describe()

crawled  text_length
count   893.000000   893.000000
mean   2017.409854   357.256439
std       3.500800   474.135102
min    2014.000000    12.000000
25%    2014.000000    96.000000
50%    2014.000000   192.000000
75%    2021.000000   409.000000
max    2021.000000  4134.000000

In [99]:
count_GINCO = pd.DataFrame({"Count": list(GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts()), "Percentage": list(round(GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts(normalize=True)*100, 2))}, index = GINCO_sheet["primary_level_1_to_X-GENRE"].value_counts().index)

print(count_GINCO.to_markdown())

|                         |   Count |   Percentage |
|:------------------------|--------:|-------------:|
| News                    |     221 |        24.75 |
| Promotion               |     209 |        23.4  |
| Information/Explanation |     139 |        15.57 |
| Opinion/Argumentation   |     131 |        14.67 |
| Other                   |      70 |         7.84 |
| Forum                   |      52 |         5.82 |
| Instruction             |      44 |         4.93 |
| Legal                   |      17 |         1.9  |
| Prose/Lyrical           |      10 |         1.12 |


In [100]:
count_GINCO

Count  Percentage
News                       221       24.75
Promotion                  209       23.40
Information/Explanation    139       15.57
Opinion/Argumentation      131       14.67
Other                       70        7.84
Forum                       52        5.82
Instruction                 44        4.93
Legal                       17        1.90
Prose/Lyrical               10        1.12

## Apply mapping to FTD sheet

In [41]:
# Apply mapping to the sheet with all information

FTD_sheet = pd.read_csv("data-sheets-with-all-info/FTD-dataset-with-all-information.csv", sep = "\t", index_col= 0)
FTD_sheet.head(5)

ID              labels Multiple labels  \
0  __id__1-syndicate  A1 (argumentative)             NaN   
1  __id__2-syndicate  A1 (argumentative)             NaN   
2  __id__3-syndicate  A1 (argumentative)             NaN   
3  __id__4-syndicate  A1 (argumentative)             NaN   
4  __id__5-syndicate  A1 (argumentative)             NaN   

                                                text  length  \
0  BMW's and Chinese Justice * * * * * In most pl...     975   
1  China and a New Balance of Power SHANGHAI – Th...     956   
2  China and Russia in the New World Disorder Can...     978   
3  The Roots of Chinese / Japanese Rivalry BOSTON...     957   
4  China's Cyber-Warriors NEW DELHI – The world n...    1034   

       GINCO_downcast_pred MT-GINCO_downcast_pred CORE_main_pred  \
0           News/Reporting         News/Reporting      Narrative   
1  Information/Explanation  Opinion/Argumentation        Opinion   
2    Opinion/Argumentation  Opinion/Argumentation        Opinion   
3    Opinion/Argumentation  Opinion/Argumentation      Narrative   
4           News/Reporting         News/Reporting      Narrative   

        CORE_sub_pred  
0    News Report/Blog  
1        Opinion Blog  
2        Opinion Blog  
3  Historical Article  
4    News Report/Blog

In [42]:
FTD_sheet.columns

Index(['ID', 'labels', 'Multiple labels', 'text', 'length',
       'GINCO_downcast_pred', 'MT-GINCO_downcast_pred', 'CORE_main_pred',
       'CORE_sub_pred'],
      dtype='object')

In [48]:
FTD_sheet["labels_to_X-GENRE"] = FTD_sheet["labels"].map(map_FTD).fillna("check")

FTD_sheet["labels_to_X-GENRE"]

0                     discarded
1                     discarded
2                     discarded
3                     discarded
4                     discarded
                 ...           
1681                  discarded
1682    Information/Explanation
1683                  discarded
1684                  Promotion
1685    Information/Explanation
Name: labels_to_X-GENRE, Length: 1553, dtype: object

In [50]:
# Check whether there is any NaN value in the column with mappings
# - there are some Nan values, but they are assigned to texts with multiple labels which is ok
Nan_values = FTD_sheet[FTD_sheet["labels_to_X-GENRE"] == "check"]
Nan_values
Nan_values[Nan_values["Multiple labels"] != "y"]

Empty DataFrame
Columns: [ID, labels, Multiple labels, text, length, GINCO_downcast_pred, MT-GINCO_downcast_pred, CORE_main_pred, CORE_sub_pred, labels_to_X-GENRE]
Index: []

In [46]:
# Save the new sheet
FTD_sheet.to_csv("data-sheets-with-all-info/FTD-dataset-with-all-information.csv", sep = "\t")

In [51]:
# Analyze distribution of labels according to the new mapping
count = pd.DataFrame({"Count": list(FTD_sheet["labels_to_X-GENRE"].value_counts()), "Percentage": list(FTD_sheet["labels_to_X-GENRE"].value_counts(normalize=True))}, index = FTD_sheet["labels_to_X-GENRE"].value_counts().index)

print(count.to_markdown())

|                         |   Count |   Percentage |
|:------------------------|--------:|-------------:|
| discarded               |     364 |    0.234385  |
| Promotion               |     256 |    0.164842  |
| Information/Explanation |     247 |    0.159047  |
| Instruction             |     165 |    0.106246  |
| check                   |     139 |    0.0895042 |
| News                    |     136 |    0.0875724 |
| Prose/Lyrical           |      94 |    0.060528  |
| Opinion/Argumentation   |      79 |    0.0508693 |
| Legal                   |      73 |    0.0470058 |


In [52]:
# Discard the "discarded" labels and those that have "check"
# (in the case of FTD, these are the texts with multiple labels)
# to calculate distribution without them
FTD_sheet = FTD_sheet[FTD_sheet["labels_to_X-GENRE"] != "discarded"]
FTD_sheet = FTD_sheet[FTD_sheet["labels_to_X-GENRE"] != "check"]

FTD_sheet.describe()

length
count    1050.000000
mean     1417.837143
std      5463.628431
min        31.000000
25%       200.000000
50%       417.000000
75%      1105.250000
max    146922.000000

In [102]:
count_FTD = pd.DataFrame({"Count": list(FTD_sheet["labels_to_X-GENRE"].value_counts()), "Percentage": list(round(FTD_sheet["labels_to_X-GENRE"].value_counts(normalize=True)*100, 2))}, index = FTD_sheet["labels_to_X-GENRE"].value_counts().index)

print(count_FTD.to_markdown())

|                         |   Count |   Percentage |
|:------------------------|--------:|-------------:|
| Promotion               |     256 |        24.38 |
| Information/Explanation |     247 |        23.52 |
| Instruction             |     165 |        15.71 |
| News                    |     136 |        12.95 |
| Prose/Lyrical           |      94 |         8.95 |
| Opinion/Argumentation   |      79 |         7.52 |
| Legal                   |      73 |         6.95 |


## Apply mapping to CORE

In [86]:
# Apply mapping to the sheet with all information

CORE_sheet = pd.read_csv("data-sheets-with-all-info/CORE-all-information.csv", sep = "\t", index_col= 0)
CORE_sheet.head(5)

label                                               text  split  \
0  NA OP SR OB  The Top TEN 'Whiniest Sets of Fans' in English...  train   
1        NA NE  Ferry consultation needs deeper questions, say...  train   
2        ID DF  I'v been recording and mixing music for about ...  train   
3        NA SR  The 25-year-old did have chances at Anfield. B...  train   
4     NA IN HA  Elizabethan Science and Technology Elizabethan...  train   

  main_labels sublabels  Len  main_len  sub_len      GINCORE  \
0       NA OP     SR OB    4         2        2  NA OP SR OB   
1         NaN        NE    2         1        1         News   
2          ID        DF    2         1        1        Forum   
3         NaN        SR    2         1        1         News   
4       NA IN        HA    3         2        1     NA IN HA   

           full_names  main_labels_full_names FTD_pred GINCO_downcast_pred  \
0               SR OB                   NA OP      NaN                 NaN   
1    News Report/Blog               Narrative      NaN                 NaN   
2    Discussion Forum  Interactive Discussion      NaN                 NaN   
3       Sports Report               Narrative      NaN                 NaN   
4  Historical Article                   NA IN      NaN                 NaN   

  MT-GINCO_downcast_pred  
0                    NaN  
1                    NaN  
2                    NaN  
3                    NaN  
4                    NaN

In [87]:
CORE_sheet.columns

Index(['label', 'text', 'split', 'main_labels', 'sublabels', 'Len', 'main_len',
       'sub_len', 'GINCORE', 'full_names', 'main_labels_full_names',
       'FTD_pred', 'GINCO_downcast_pred', 'MT-GINCO_downcast_pred'],
      dtype='object')

In [88]:
CORE_sheet["subcategories_to_X-GENRE"] = CORE_sheet["full_names"].map(map_CORE).fillna("check")

CORE_sheet["subcategories_to_X-GENRE"]

0                        check
1                         News
2                        Forum
3                         News
4                    discarded
                 ...          
48444                     News
48445                discarded
48446    Opinion/Argumentation
48447                     News
48448                    check
Name: subcategories_to_X-GENRE, Length: 48420, dtype: object

In [89]:
# Check whether there is any NaN value in the column with mappings
# - there are some Nan values, but they are assigned to texts with multiple labels which is ok
Nan_values = CORE_sheet[CORE_sheet["subcategories_to_X-GENRE"] == "check"]

Nan_values["sub_len"].value_counts()

1    4932
2    3622
Name: sub_len, dtype: int64

In [95]:
4932+3622

8554

In [92]:
texts_to_check = Nan_values[Nan_values["sub_len"] == 1]
texts_to_check

label                                               text  split  \
27        IN  There are some things you just can't Google......  train   
39        OP  My top 6 handy kitchen tips I'm always on the ...  train   
55     OTHER  Blogging as a Supplement to Peer Review: My 20...  train   
75       NA   KURDISTAN: The right to be in power Wednesday,...  train   
76        IN  Putting Nature Back Into the Natural Beauty of...  train   
...      ...                                                ...    ...   
48426     IN  Analysing a whole poem Topics 1-4 have been co...    dev   
48431    NA   Catch Up On...THE WAR IN IRAQ (Megoracle's Fir...    dev   
48442  OTHER  Last Friday I gave a talk to a group of just o...    dev   
48443    NA   As a prisoner of war in Vietnam, Eagle Scout G...    dev   
48448  IN OP  2009 September 14th The folks over at VGBlogge...    dev   

      main_labels sublabels  Len  main_len  sub_len                  GINCORE  \
27             IN       NaN    1         1        1  Information/Explanation   
39             OP       NaN    1         1        1    Opinion/Argumentation   
55          OTHER       NaN    1         1        1                  discard   
75            NaN       NaN    2         1        1                  discard   
76             IN       NaN    1         1        1  Information/Explanation   
...           ...       ...  ...       ...      ...                      ...   
48426          IN       NaN    1         1        1  Information/Explanation   
48431         NaN       NaN    2         1        1                  discard   
48442       OTHER       NaN    1         1        1                  discard   
48443         NaN       NaN    2         1        1                  discard   
48448       IN OP       NaN    2         2        1                  discard   

      full_names                 main_labels_full_names FTD_pred  \
27           NaN  Informational Description/Explanation      NaN   
39           NaN                                Opinion      NaN   
55           NaN                                  Other      NaN   
75           NaN                              Narrative      NaN   
76           NaN  Informational Description/Explanation      NaN   
...          ...                                    ...      ...   
48426        NaN  Informational Description/Explanation      NaN   
48431        NaN                              Narrative      NaN   
48442        NaN                                  Other      NaN   
48443        NaN                              Narrative      NaN   
48448        NaN                                  IN OP      NaN   

      GINCO_downcast_pred MT-GINCO_downcast_pred subcategories_to_X-GENRE  
27                    NaN                    NaN                    check  
39                    NaN                    NaN                    check  
55                    NaN                    NaN                    check  
75                    NaN                    NaN                    check  
76                    NaN                    NaN                    check  
...                   ...                    ...                      ...  
48426                 NaN                    NaN                    check  
48431                 NaN                    NaN                    check  
48442                 NaN                    NaN                    check  
48443                 NaN                    NaN                    check  
48448                 NaN                    NaN                    check  

[4932 rows x 15 columns]

 3622 texts are not mapped, because they have multiple labels, 4932 are not mapped because they were annotated only with main CORE labels and with no subcategories.

In [93]:
# Save the new CORE sheet
CORE_sheet.to_csv("data-sheets-with-all-info/CORE-all-information.csv", sep = "\t")

In [94]:
# Analyze distribution of labels according to the new mapping
count = pd.DataFrame({"Count": list(CORE_sheet["subcategories_to_X-GENRE"].value_counts()), "Percentage": list(CORE_sheet["subcategories_to_X-GENRE"].value_counts(normalize=True))}, index = CORE_sheet["subcategories_to_X-GENRE"].value_counts().index)

print(count.to_markdown())

|                         |   Count |   Percentage |
|:------------------------|--------:|-------------:|
| News                    |   13323 |  0.275155    |
| discarded               |   11211 |  0.231537    |
| Opinion/Argumentation   |    8979 |  0.18544     |
| check                   |    8554 |  0.176663    |
| Forum                   |    1950 |  0.0402726   |
| Instruction             |    1528 |  0.0315572   |
| Information/Explanation |    1344 |  0.0277571   |
| Prose/Lyrical           |     842 |  0.0173895   |
| Other                   |     490 |  0.0101198   |
| Legal                   |     186 |  0.00384139  |
| Promotion               |      13 |  0.000268484 |


In [97]:
# Discard the "discarded" labels and those that have "check"
# (in the case of CORE, these are the texts with multiple labels or no CORE subcategory label)
# to calculate distribution without them
CORE_sheet = CORE_sheet[CORE_sheet["subcategories_to_X-GENRE"] != "discarded"]
CORE_sheet = CORE_sheet[CORE_sheet["subcategories_to_X-GENRE"] != "check"]

CORE_sheet.describe()

Len      main_len  sub_len
count  28655.000000  28655.000000  28655.0
mean       2.059536      1.059536      1.0
std        0.236629      0.236629      0.0
min        2.000000      1.000000      1.0
25%        2.000000      1.000000      1.0
50%        2.000000      1.000000      1.0
75%        2.000000      1.000000      1.0
max        3.000000      2.000000      1.0

In [103]:
# Analyze distribution of labels according to the new mapping
count_CORE = pd.DataFrame({"Count": list(CORE_sheet["subcategories_to_X-GENRE"].value_counts()), "Percentage": list(round(CORE_sheet["subcategories_to_X-GENRE"].value_counts(normalize=True)*100, 2))}, index = CORE_sheet["subcategories_to_X-GENRE"].value_counts().index)

print(count_CORE.to_markdown())

|                         |   Count |   Percentage |
|:------------------------|--------:|-------------:|
| News                    |   13323 |        46.49 |
| Opinion/Argumentation   |    8979 |        31.33 |
| Forum                   |    1950 |         6.81 |
| Instruction             |    1528 |         5.33 |
| Information/Explanation |    1344 |         4.69 |
| Prose/Lyrical           |     842 |         2.94 |
| Other                   |     490 |         1.71 |
| Legal                   |     186 |         0.65 |
| Promotion               |      13 |         0.05 |


In [104]:
count_FTD.Percentage

Promotion                  24.38
Information/Explanation    23.52
Instruction                15.71
News                       12.95
Prose/Lyrical               8.95
Opinion/Argumentation       7.52
Legal                       6.95
Name: Percentage, dtype: float64

In [108]:
# make dataframe
merged_df = pd.DataFrame({"GINCO":count_GINCO.Percentage, "FTD":count_FTD.Percentage, "CORE": count_CORE.Percentage})

merged_df.fillna(0, inplace=True)

print(merged_df.to_markdown())

|                         |   GINCO |   FTD |   CORE |
|:------------------------|--------:|------:|-------:|
| Forum                   |    5.82 |  0    |   6.81 |
| Information/Explanation |   15.57 | 23.52 |   4.69 |
| Instruction             |    4.93 | 15.71 |   5.33 |
| Legal                   |    1.9  |  6.95 |   0.65 |
| News                    |   24.75 | 12.95 |  46.49 |
| Opinion/Argumentation   |   14.67 |  7.52 |  31.33 |
| Other                   |    7.84 |  0    |   1.71 |
| Promotion               |   23.4  | 24.38 |   0.05 |
| Prose/Lyrical           |    1.12 |  8.95 |   2.94 |
